### PR TITLE
fixbug 升级依赖，解决无法连接neo4j+s的问题

### PR DESCRIPTION
**Pull request by Gahao**
### 👀 PR includes

✨ Feature

- [ x] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [ ] Solve the issue and close #0

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌     | ✅    |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by pomelo-nwu** [comment]
@Gahao 感谢贡献，升级了版本就 okay 了？晚点我测试下

**Comment by Gahao** [comment]
你的邮件已经收到= =请放心嘉豪

**Comment by Hisnameandhe** [comment]
这个能合到主分支了吗？ 目前导出的html单页仍然无法访问

**Comment by Gahao** [comment]
你的邮件已经收到= =请放心嘉豪

**Pull request closed without merging**
